///// swiper slider javaScript
var swiper = new Swiper(".mySwiper", {
    autoplay: {
        delay: 3000,
        disableOnInteraction: false,
      },
      loop: true,
      speed: 500
});

///// mobile menu javaScript
document.addEventListener("DOMContentLoaded", function () {
    const menuToggle = document.getElementById("menuToggle");
    const menuIcon = document.getElementById("menuIcon");
    const closeIcon = document.getElementById("closeIcon");
    const mobileMenu = document.getElementById("mobileMenu");

    menuToggle.addEventListener("click", function () {
        mobileMenu.classList.toggle("hidden");
        menuIcon.classList.toggle("hidden");
        closeIcon.classList.toggle("hidden");
    });
});

///// language change javaScript
const translations = {
    bn: {
        campous: "ক্যাম্পাস",
        about: "আমাদের সম্পর্কে",
        history: "ইতিহাস",
        aims: "লক্ষ্য ও উদ্দেশ্য",
        industrial: "প্রাতিষ্ঠানিক কাঠামো",
        admission: "ভর্তি",
        apply: "কিভাবে আবেদন করতে হবে",
        application: "আবেদন",
        exam: "ভর্তি পরীক্ষা",
        admitionpolicy: "ভর্তি নীতি",
        educationsystem: "বর্তমান শিক্ষা ব্যবস্থা",
        Technologies: "টেকনোলজিসমূহ",
        Computer: "কম্পিউটার সায়েন্স",
        civil: "সিভিল",
        Electrical: "ইলেকট্রিক্যাল",
        Architecture: "আর্কিটেকচার",
        Administration: "প্রশাসন",
        principal: "অধ্যক্ষ",
        viceprincipal: "উপাধ্যক্ষ",
        AcademicCouncil: "একাডেমিক কাউন্সিল",
        Teachers: "শিক্ষক শিক্ষিকামণ্ডলী",
        Directors: "পরিচালকবৃন্দ",
        Academicactivities: "একাডেমিক কার্যক্রম",
        Classification: "শ্রেণিসূচি",
        OnlineClassSchedule: "অনলাইন শ্রেণিসূচি",
        ExamSchedule: "পরীক্ষার সময়সূচি",
        AcademicSyllabus: "একাডেমিক সিলেবাস",
        Academiccalendar: "শিক্ষা বর্ষপঞ্জি",
        student: "শিক্ষার্থী",
        Studentuniform: "শিক্ষার্থী ইউনিফর্ম",
        Testsystem: "পরীক্ষা ব্যবস্থা",
        Rulesregulations: "নিয়ম এবং প্রবিধান",
        ourstudents: "আমাদের শিক্ষার্থী",
        Studentsuccess: "শিক্ষার্থীদের সাফল্য",
        result: "ফলাফল",
        InternalTestResults: "অভ্যন্তরীণ পরীক্ষার ফলাফল",
        BoardExamResult: "বোর্ড পরীক্ষার ফলাফল",
        Resource: "রিসোর্স",
        Digitalclasscontent: "ডিজিটাল ক্লাস কনটেন্ট",
        Library: "গ্রন্থাগার",
        ComputerLab: "কম্পিউটার ল্যাব",
        Playground: "খেলার মাঠ",
        ICTClub: "আইসিটি ক্লাব",
        Gallery: "গ্যালারি",
        Photogallery: "ছবি গ্যালারি",
        Videogallery: "ভিডিও গ্যালারি",
        NoticeCorner: "নোটিশ কর্নার",
        Allnotices: "সকল নোটিশ",
        JobCorner: "জব কর্ণার",
        Notices: "নোটিশ",
        marqueenotice: "***শিক্ষার্থীদের অবগতির জন্য জানানো যাচ্ছে যে ১৮ মার্চ ২০২৫ ইং তারিখ থেকে পর্ব-মধ্য পরীক্ষা অনুষ্ঠিত হবে।",
        Notice: "নোটিশ",
        midtermexams: "পর্ব-মধ্য পরীক্ষা সংক্রান্ত নোটিশ।",
        date1: "(১৮ মার্চ ২০২৫)",
        Noticeregarding: "কমপেক্ট পলিটেকনিক ইনস্টিটিউটের আইসিটি ক্লাবের ছাত্র প্রতিনিধি অনুমোদন সম্পর্কিত নোটিশ।",
        date2: "(২৬ ফেব্রুয়ারী, ২০২৫)",
        Download: "ডাউনলোড",
        Jobplacement: "জব প্লেসমেন্ট",
        Events: "ইভেন্টস",
        Principal: "অধ্যক্ষ",
        IglooRoy: "ইগলু রায়",
        CompactPolytechnic: "কমপেক্ট পলিটেকনিক ইনস্টিটিউট",
        BangladeshTechnical: "বাংলাদেশ কারিগরি শিক্ষা বোর্ড",
        DirectorateofTechnical: "কারিগরি শিক্ষা অধিদপ্তর",
        Contactforinformation: "তথ্য প্রাপ্তির জন্য যোগাযোগ",
        NTVQFwebsite: "NTVQF ওয়েবসাইট",
        DepartmentofSecondary: "মাধ্যমিক ও উচ্চ শিক্ষা বিভাগ",
        PrimeMinister: "প্রধানমন্ত্রীর শিক্ষা সহায়তা ট্রাস্ট",
        nationalanthem: "জাতীয় সংগীত",
        Emergencyhotline: "জরুরি হটলাইন",
        InstituteLocation: "ইনস্টিটিউট লোকেশন",
        CollageLocation: "একাডেমি রোড - ৩৯০০, ফেনী, বাংলাদেশ।",
        Sequential: "ক্রমিক",
        Title: "শিরোনাম",
        Releasedate: "প্রকাশের তারিখ",
        Download: "ডাউনলোড",
        NumberOne: "১",
        NumberTwo: "২",
        Bangladesboard: "বাংলাদেশ কারিগরি শিক্ষাবোর্ড (BTEB) কর্তৃক অনুমোদিত",
        compacttext: "কমপেক্ট পলিটেকনিক ইনস্টিটিউট",
        aboutustext: "বাংলাদেশের অন্যতম বেসরকারি পলিটেকনিক ইনস্টিটিউট। ডিপ্লোমা ইন ইঞ্জিনিয়ারিং শিক্ষাক্রম পরিচালনায় প্রায় এক যুগের ও বেশি সময় ধরে আমাদের অভিজ্ঞতা রয়েছে। কারিগরি শিক্ষায় দক্ষ মানব শক্তি এবং দক্ষ ডিপ্লোমা ইঞ্জিনিয়ার হিসেবে গড়ে তুলতে আমাদের রয়েছে ০৪ বছর মেয়াদী ডিপ্লোমা ইন ইঞ্জিনিয়ারিং শিক্ষাক্রমের মোট ০৪ টি টেকনোলজি।",
        technologyAbout: "টেকনোলজি সমূহঃ",
        cst: "কম্পিউটার সায়েন্স এন্ড টেকনোলজি",
        et: "ইলেকট্রিক্যাল টেকনোলজি",
        ct: "সিভিল টেকনোলজি",
        at: "আর্কিটেকচার টেকনোলজি",
        cpiteachers: "CPI রয়েছে দক্ষ শিক্ষক/শিক্ষিকামন্ডলী, শিক্ষার্থীদের হোস্টেল সুবিধা এবং আধুনিক যন্ত্রপাতি সমৃদ্ধ ব্যাবহারিক ল্যাব।",
        technologybased: "কমপেক্ট পলিটেকনিক ইনস্টিটিউট (CPI) – প্রযুক্তিনির্ভর উৎকর্ষের প্রতীক",
        developingskilled: "(CPI) বাংলাদেশের অন্যতম শীর্ষস্থানীয় বেসরকারি পলিটেকনিক প্রতিষ্ঠান। প্রযুক্তিগত উৎকর্ষ ও মানসম্পন্ন শিক্ষার সমন্বয়ে CPI দক্ষ জনশক্তি গড়ে তুলতে প্রতিশ্রুতিবদ্ধ।",
        demandtechnical: "বৈশ্বিক ও স্থানীয় পর্যায়ে কারিগরি শিক্ষার চাহিদা ক্রমাগত বৃদ্ধি পাচ্ছে, এবং CPI এই চাহিদা পূরণে নিরলসভাবে কাজ করে যাচ্ছে। ২০১০ সালে মাত্র কয়েকটি টেকনোলজি নিয়ে যাত্রা শুরু করা এই প্রতিষ্ঠানটি বর্তমানে একটি বিস্তৃত পরিবারে পরিণত হয়েছে এবং ক্রমবর্ধমান চাহিদার সাথে তাল মিলিয়ে দ্রুত সম্প্রসারিত হচ্ছে।",
        Whystudy: "CPI-তে কেন পড়বেন?",
        Moderncurriculum: "আধুনিক পাঠ্যক্রম – শিল্প ও প্রযুক্তির সাম্প্রতিক উন্নতির সাথে সামঞ্জস্যপূর্ণ কোর্স",
        Experiencedtrainers: "অভিজ্ঞ প্রশিক্ষক – বাস্তবমুখী প্রশিক্ষণে দক্ষ শিক্ষকমণ্ডলী",
        ConnectingEducation: "শিক্ষা ও কর্মসংস্থানের সংযোগ – শিক্ষার্থীদের ক্যারিয়ার গঠনে কার্যকর দিকনির্দেশনা",
        CPIcommitted: "CPI তার শিক্ষার্থীদের ভবিষ্যতের প্রযুক্তিনির্ভর কর্মসংস্থানে নেতৃত্ব দেওয়ার উপযোগী করে গড়ে তুলতে অঙ্গীকারবদ্ধ।",
        committeddeveloping: "কমপেক্ট পলিটেকনিক ইনস্টিটিউট (CPI) উচ্চমানের কারিগরি শিক্ষার মাধ্যমে দক্ষ ও যোগ্য ডিপ্লোমা ইঞ্জিনিয়ার গড়ে তোলার জন্য প্রতিশ্রুতিবদ্ধ। আমাদের লক্ষ্য শিক্ষার্থীদের প্রযুক্তিগত দক্ষতা ও নৈতিক মূল্যবোধের সমন্বয়ে ভবিষ্যতের চ্যালেঞ্জ মোকাবিলা করার উপযোগী করে গড়ে তোলা।",
        Ourgoals: "আমাদের প্রধান লক্ষ্য ও উদ্যোগ:",
        ensuremutual: "শিক্ষক, কর্মচারী ও শিক্ষার্থীদের মধ্যে পারস্পরিক ঐক্য ও সহযোগিতা নিশ্চিত করা।",
        Toenhance: "প্রশিক্ষণের মাধ্যমে শিক্ষকদের দক্ষতা বৃদ্ধি করা।",
        createquality: "উন্নত অবকাঠামো ও লজিস্টিক সুবিধা প্রদান করে মানসম্পন্ন শিক্ষার পরিবেশ তৈরি করা।",
        Maintaingood: "স্থানীয় সম্প্রদায় ও সংশ্লিষ্ট কর্তৃপক্ষের সঙ্গে সুসম্পর্ক বজায় রাখা।",
        makeeducation: "শিক্ষা ও তথ্য বিনিময় পদ্ধতিকে আধুনিক ও প্রযুক্তিনির্ভর করা।",
        Increaseemployment: "শিক্ষার সঙ্গে শিল্প ও বাজারের সংযোগ নিশ্চিত করে কর্মসংস্থানের সুযোগ বৃদ্ধি করা।",
        helpstudents: "সহ-পাঠ্যক্রমিক কার্যক্রমের মাধ্যমে শিক্ষার্থীদের নৈতিকতা ও ব্যক্তিত্ব বিকাশে সহায়তা করা।",
        Ensuringspecial: "নারী শিক্ষার্থীদের জন্য বিশেষ সুযোগ-সুবিধা ও সহায়ক পরিবেশ নিশ্চিত করা।",
        believesthat: "CPI বিশ্বাস করে যে প্রযুক্তিগত দক্ষতা, নৈতিক মূল্যবোধ এবং শিল্প সংযোগের সমন্বয়ে দক্ষ ও প্রতিযোগিতামূলক ডিপ্লোমা ইঞ্জিনিয়ার গড়ে তোলা সম্ভব।",
        globalizationacquiring: "বিশ্বায়নের এই যুগে প্রতিযোগিতায় টিকে থাকতে ও আধুনিক বিশ্ব চাহিদার সঙ্গে তাল মিলিয়ে চলতে প্রযুক্তিগত দক্ষতা অর্জন অপরিহার্য। দেশের বিশাল জনগোষ্ঠীকে আধুনিক প্রযুক্তির সঙ্গে সম্পৃক্ত করে দক্ষ মানবসম্পদে পরিণত করা এখন সময়ের দাবি। তথ্য ও প্রযুক্তি শিক্ষার সুযোগ বৃদ্ধি করে জনশক্তির দক্ষতা ও কর্মপরিধির প্রসার ঘটাতে হবে।",
        developedcountries: "পৃথিবীর উন্নত দেশগুলোর তুলনায় কারিগরি শিক্ষায় শিক্ষিত জনগোষ্ঠীর হার আমাদের দেশে এখনো কম। তবে, সাম্প্রতিক বছরগুলোতে কারিগরি শিক্ষার প্রতি মানুষের আগ্রহ বৃদ্ধি পেয়েছে এবং এই খাতে একটি গণজাগরণ সৃষ্টি হচ্ছে। ইতোমধ্যে বাংলাদেশে কারিগরি শিক্ষার প্রসারে বিভিন্ন প্রকল্প গ্রহণ করা হয়েছে। এর মধ্যে অন্যতম হলো— পলিটেকনিক ইনস্টিটিউটে অধ্যয়নরত শিক্ষার্থীদের মাসিক বৃত্তির ব্যবস্থা ও চাকরির নিশ্চয়তা। পাশাপাশি, শিক্ষা পদ্ধতিকে আন্তর্জাতিক মানের সঙ্গে সামঞ্জস্যপূর্ণ করে তোলার উদ্যোগ নেওয়া হয়েছে।",
        Consideringthese: 'এসব চাহিদার কথা বিবেচনা করেই ২০১০ সালে চট্টগ্রাম বিভাগের ফেনী জেলায় প্রতিষ্ঠিত হয় "কমপেক্ট পলিটেকনিক ইনস্টিটিউট (CPI)" —একটি আধুনিক ও উন্নত মানের বেসরকারি পলিটেকনিক ইনস্টিটিউট। এখানে বাংলাদেশ কারিগরি শিক্ষা বোর্ড (BTEB)-এর অধীনে ৪ বছর মেয়াদী ডিপ্লোমা-ইন-ইঞ্জিনিয়ারিং প্রোগ্রাম পরিচালিত হচ্ছে। বর্তমানে আর্কিটেকচার, সিভিল, ইলেকট্রিক্যাল, এবং কম্পিউটার সায়েন্স অ্যান্ড টেকনোলজি বিভাগে শিক্ষার্থীদের প্রশিক্ষণ দেওয়া হচ্ছে।',
        Theexpansion: "কারিগরি শিক্ষার প্রসারের মাধ্যমে দেশে তথ্যপ্রযুক্তি সচেতনতা ও আত্মনির্ভরশীলতা বৃদ্ধি পাবে, দারিদ্র্য ও বেকারত্ব হ্রাস পাবে এবং দক্ষ জনশক্তি রপ্তানির মাধ্যমে দেশ সমৃদ্ধ হবে। আগ্রহী শিক্ষার্থীদের কমপেক্ট পলিটেকনিক ইনস্টিটিউটে যোগদানের জন্য আন্তরিক আমন্ত্রণ জানাচ্ছি।",
        AnjumanAra: "আঞ্জুমান আরা",
        AbdulAhad: "আব্দুল আহাদ",
        TanjinaHafiz: "তানজিনা হাফিজ",
        HeadDepartment: "বিভাগীয় প্রধান",
        osmangoni: "মোহাম্মদ ওসমান গনি",
        juniorinstructor: "জুনিয়র ইন্সট্রাক্টর",
        CurriculumTechnology: "পাঠ্যক্রম ও টেকনোলজি",
        DiplomaEngineering: "ডিপ্লোমা ইন ইঞ্জিনিয়ারিং: ৪ বছর মেয়াদী কোর্স",
        CurriculumBangladesh: "পাঠ্যক্রম: বাংলাদেশ কারিগরি শিক্ষাবোর্ড (BTEB) অনুমোদিত",
        Technologyprovided: "প্রদানকৃত টেকনোলজি: (যেমন – সিভিল, ইলেকট্রিক্যাল, কম্পিউটার, ইত্যাদি)",
        Typeeducation: "শিক্ষার ধরন: তাত্ত্বিক ও ব্যবহারিক ক্লাস",
        researchfacilities: "ল্যাব ও গবেষণা সুবিধা",
        equippedlaboratory: "আধুনিক ও সুসজ্জিত ল্যাবরেটরি",
        Researchopportunities: "গবেষণার সুযোগ এবং ইনোভেটিভ প্রজেক্ট ডেভেলপমেন্ট",
        Teacherskills: "শিক্ষকদের দক্ষতা ও প্রশিক্ষণ",
        Experiencedtrained: "অভিজ্ঞ ও প্রশিক্ষিত শিক্ষকবৃন্দ",
        Specialseminars: "অতিথি বক্তাদের মাধ্যমে বিশেষ সেমিনার ও ওয়ার্কশপ",
        CareerGuidelines: "ক্যারিয়ার গাইডলাইন ও ইন্ডাস্ট্রি সংযোগ",
        Industrybased: "ইন্ডাস্ট্রি ভিত্তিক ট্রেনিং ও ইন্টার্নশিপ",
        CampusRecruitment: "ক্যাম্পাস রিক্রুটমেন্ট ও চাকরি সহায়তা",
        Careercounseling: "শিক্ষার্থীদের জন্য ক্যারিয়ার কাউন্সেলিং ও পরামর্শ সেবা",
        Cocurricularactivities: "সহ-পাঠ্যক্রমিক কার্যক্রম",
        TechnicalProject: "টেকনিক্যাল প্রোজেক্ট কম্পিটিশন",
        Studentorganizations: "ছাত্র সংগঠন ও ক্লাব",
        culturalactivities: "স্পোর্টস, ডিবেট ও সাংস্কৃতিক কার্যক্রম",
        Studentfacilities: "ছাত্র-ছাত্রীদের সুযোগ-সুবিধা",
        LibraryStudy: "লাইব্রেরি ও স্টাডি সেন্টার",
        Hostelfacilities: "হোস্টেলের সুবিধা",
        Listallteachers: "সকল শিক্ষক শিক্ষিকামণ্ডলীর তালিকা"
    },
    en: {
        campous: "Campus",
        about: "About us",
        history: "History",
        aims: "Aims and objectives",
        industrial: "Institutional structure",
        admission: "Admission",
        apply: "How to apply",
        application: "application",
        exam: "Admission test",
        admitionpolicy: "Admission policy",
        educationsystem: "Current education system",
        Technologies: "Technologies",
        Computer: "Computer Science",
        civil: "Civil",
        Electrical: "Electrical",
        Architecture: "Architecture",
        Administration: "Administration",
        principal: "Principal",
        viceprincipal: "Vice principal",
        AcademicCouncil: "Academic council",
        Teachers: "Teachers",
        Directors: "Directors",
        Academicactivities: "Academic activities",
        Classification: "Classification",
        OnlineClassSchedule: "Online class schedule",
        ExamSchedule: "Exam Schedule",
        AcademicSyllabus: "Academic syllabus",
        Academiccalendar: "Academic calendar",
        student: "Student",
        Studentuniform: "Student uniform",
        Testsystem: "Examination system",
        Rulesregulations: "Rules and regulations",
        ourstudents: "Our students",
        Studentsuccess: "Student success",
        result: "Result",
        InternalTestResults: "Internal test results",
        BoardExamResult: "Board exam result",
        Resource: "Resource",
        Digitalclasscontent: "Digital class content",
        Library: "Library",
        ComputerLab: "Computer lab",
        Playground: "Playground",
        ICTClub: "ICT Club",
        Gallery: "Gallery",
        Photogallery: "Photo gallery",
        Videogallery: "Video gallery",
        NoticeCorner: "Notice corner",
        Allnotices: "All notices",
        JobCorner: "Job corner",
        Notices: "Notice",
        marqueenotice: "***For the information of students, it is hereby informed that the mid-term examination will be held from March 18, 2025.",
        Notice: "Notice",
        midtermexams: "Notice regarding mid-term exams.",
        date1: "(18 March 2025)",
        Noticeregarding: "Notice regarding approval of student representative of ICT Club of Compact Polytechnic Institute.",
        date2: "(February 26, 2025)",
        Download: "Download",
        Jobplacement: "Job placement",
        Events: "Events",
        Principal: "Principal",
        IglooRoy: "Igloo Roy",
        CompactPolytechnic: "Compact Polytechnic Institute",
        BangladeshTechnical: "Bangladesh Technical Education Board",
        DirectorateofTechnical: "Directorate of Technical Education",
        Contactforinformation: "Contact for information",
        NTVQFwebsite: "NTVQF website",
        DepartmentofSecondary: "Department of Secondary and Higher Education",
        PrimeMinister: "Prime Minister's Education Assistance Trust",
        nationalanthem: "national Anthem",
        Emergencyhotline: "Emergency Hotline",
        InstituteLocation: "Institute Location",
        CollageLocation: "Academy Road - 3900, Feni, Bangladesh.",
        Sequential: "Sequential",
        Title: "Title",
        Releasedate: "Release date",
        Download: "Download",
        NumberOne: "1",
        NumberTwo: "2",
        Bangladesboard: "Bangladesh Technical Education Board",
        compacttext: "Compact Polytechnic Institute",
        aboutustext: "One of the leading private polytechnic institutes in Bangladesh. We have over a decade of experience in conducting Diploma in Engineering programs. To develop skilled manpower and competent diploma engineers in technical education, we offer a 4-year Diploma in Engineering program in a total of four different technologies.",
        technologyAbout: "Technologies:",
        cst: "Computer Science and Technology",
        et: "Electrical Technology",
        ct: "Civil Technology",
        at: "Architecture Technology",
        cpiteachers: "CPI has skilled teachers, hostel facilities for students, and practical labs equipped with modern equipment.",
        technologybased: "Compact Polytechnic Institute (CPI) – A symbol of technology-based excellence",
        developingskilled: "(CPI) is one of the leading private polytechnic institutions in Bangladesh. CPI is committed to developing a skilled workforce through a combination of technological excellence and quality education.",
        demandtechnical: "The demand for technical education is steadily increasing both globally and locally, and CPI is relentlessly working to meet this demand. Established in 2010 with only a few technologies, the institution has now grown into a vast family and is rapidly expanding to keep pace with the rising demand.",
        Whystudy: "Why study at CPI?",
        Moderncurriculum: "Modern curriculum – courses in line with recent advances in industry and technology",
        Experiencedtrainers: "Experienced trainers – skilled teachers in practical training",
        ConnectingEducation: "Connecting Education and Employment – ​​Effective Guidance for Students in Career Formation",
        CPIcommitted: "CPI is committed to preparing its students to lead the technology-driven workforce of the future.",
        committeddeveloping: "Compact Polytechnic Institute (CPI) is committed to developing skilled and qualified Diploma Engineers through high quality technical education. Our aim is to equip students with a combination of technical skills and ethical values ​​to meet the challenges of the future.",
        Ourgoals: "Our main goals and initiatives:",
        ensuremutual: "To ensure mutual unity and cooperation among teachers, staff and students.",
        Toenhance: "To enhance the skills of teachers through training.",
        createquality: "To create a quality learning environment by providing advanced infrastructure and logistical facilities.",
        Maintaingood: "Maintain good relations with the local community and relevant authorities.",
        makeeducation: "To make education and information exchange systems modern and technology-based.",
        Increaseemployment: "Increase employment opportunities by ensuring linkages between education, industry and the market.",
        helpstudents: "To help students develop their moral and personality through co-curricular activities.",
        Ensuringspecial: "Ensuring special facilities and a supportive environment for female students.",
        believesthat: "CPI believes that it is possible to develop skilled and competitive diploma engineers by combining technical skills, ethical values, and industry connections.",
        globalizationacquiring: "In this era of globalization, acquiring technological skills is essential to stay competitive and meet modern global demands. It is now imperative to integrate the vast population with advanced technology and transform them into skilled human resources. Expanding opportunities for education in information and technology will enhance workforce efficiency and broaden the scope of employment.",
        developedcountries: "Compared to developed countries, the percentage of the population educated in technical education remains relatively low in our country. However, in recent years, interest in technical education has significantly increased, leading to a growing movement in this sector. Various initiatives have already been undertaken in Bangladesh to promote technical education. Notably, provisions have been made for monthly scholarships and job security for students enrolled in polytechnic institutes. Additionally, efforts are being made to align the education system with international standards.",
        Consideringthese: "Considering these demands, Compact Polytechnic Institute (CPI) was established in 2010 in Feni district, Chattogram division, as a modern and high-quality private polytechnic institute. The institute operates a four-year Diploma in Engineering program under the Bangladesh Technical Education Board (BTEB). Currently, students receive training in the Architecture, Civil, Electrical, and Computer Science & Technology departments.",
        Theexpansion: "The expansion of technical education will enhance IT awareness and self-reliance in the country, reduce poverty and unemployment, and contribute to national prosperity by exporting skilled manpower. We warmly invite aspiring students to join Compact Polytechnic Institute (CPI) and be part of this transformative journey.",
        AnjumanAra: "Anjuman Ara",
        AbdulAhad: "Abdul Ahad",
        TanjinaHafiz: "Tanjina Hafiz",
        HeadDepartment: "Head of Department",
        osmangoni: "Mohammad Osman Goni",
        juniorinstructor: "Junior Instructor",
        CurriculumTechnology: "Curriculum and Technology",
        DiplomaEngineering: "Diploma in Engineering: 4-year course",
        CurriculumBangladesh: "Curriculum: Bangladesh Technical Education Board (BTEB) approved",
        Technologyprovided: "Technology provided: (e.g. – Civil, Electrical, Computer, etc.)",
        Typeeducation: "Type of education: Theoretical and practical classes",
        researchfacilities: "Lab and research facilities",
        equippedlaboratory: "Modern and well-equipped laboratory",
        Researchopportunities: "Research opportunities and innovative project development",
        Teacherskills: "Teacher skills and training",
        Experiencedtrained: "Experienced and trained teachers",
        Specialseminars: "Special seminars and workshops through guest speakers",
        CareerGuidelines: "Career Guidelines and Industry Connections",
        Industrybased: "Industry-based training and internships",
        CampusRecruitment: "Campus Recruitment and Job Assistance",
        Careercounseling: "Career counseling and advisory services for students",
        Cocurricularactivities: "Co-curricular activities",
        TechnicalProject: "Technical Project Competition",
        Studentorganizations: "Student organizations and clubs",
        culturalactivities: "Sports, debates and cultural activities",
        Studentfacilities: "Student facilities",
        LibraryStudy: "Library and Study Centre",
        Hostelfacilities: "Hostel facilities",
        Listallteachers: "List of all teachers and teaching staff",
    }
};
function setLanguage(language) {
    document.querySelectorAll("[data-translate]").forEach(element => {
        const key = element.getAttribute("data-translate");
        element.innerText = translations[language][key];
    });
}
document.getElementById("language-selector").addEventListener("change", function() {
    setLanguage(this.value);
});
setLanguage("bn");